Repository opendatateam/udata-ods, pull requests merged in 2018-04, with the labels that each got.

#26 Do not export SHP when above records limit
  CHANGELOG.md
  tests/data/search.json
  tests/test_ods_backend.py
  udata_ods/harvesters.py
Labels: current-sprint, in progress

#29 Initial ODS preview (fix #28)
  .circleci/config.yml
  CHANGELOG.md
  requirements/install.pip
  setup.py
  tests/test_ods_backend.py
  tests/test_ods_preview.py
  udata_ods/harvesters.py
  udata_ods/templates/preview.html
  udata_ods/views.py
Labels: current-sprint, enhancement, in progress

#31 Protocol-relative preview
  .circleci/config.yml
  tests/test_ods_backend.py
  udata_ods/harvesters.py
Labels: in progress

#34 Preview plugin
  .circleci/config.yml
  CHANGELOG.md
  setup.py
  tests/test_ods_backend.py
  tests/test_ods_preview.py
  udata_ods/harvesters.py
  udata_ods/preview.py
Labels: current-sprint, enhancement, in progress
