Repository opendatateam/udata-ods, pull requests merged in 2018-03, with the labels that each got.

#14 Alternative exports support
  CHANGELOG.md
  tests/data/search.json
  tests/test_ods_backend.py
  udata_ods/harvesters.py
Labels: current-sprint, in progress

#16 Make resources permanent
  tests/test_ods_backend.py
  udata_ods/harvesters.py
Labels: current-sprint, enhancement, in progress

#20 Initial i18n support
  CHANGELOG.md
  babel.cfg
  setup.cfg
  tasks.py
  tests/test_ods_backend.py
  udata_ods/harvesters.py
  udata_ods/translations/fr/LC_MESSAGES/udata-ods.po
  udata_ods/translations/pt/LC_MESSAGES/udata-ods.po
Labels: current-sprint, i18n

#22 New Crowdin translations
  udata_ods/translations/fr/LC_MESSAGES/udata-ods.po
  udata_ods/translations/pt/LC_MESSAGES/udata-ods.po
Labels: in progress
